### ISSUE TITLE
`is` operator type

### ISSUE THREAD

**Issue by john-kelly** [john-kelly/elm-postgrest#36]
```elm
{-| Is comparison
-}
is : Maybe Bool -> (schema -> Field (Maybe Bool)) -> schema -> Filter
is =
    singleValueFilterFn Is
```

**Comment by john-kelly** [comment]
https://www.postgresql.org/docs/9.1/static/functions-comparison.html

**Comment by jbrgfx** [comment]
Can you provide an example of a filter comparison on a Boolean?

I understand the postgresql reference, but I am struggling to implement the same using elm-postgREST.  I can, however, use curl to return what I expect via the binary postgrest haskell directly using eq.true.

The utility of the package is really impressive.

**Comment by jbrgfx** [comment]
I succeeded using:
 . . . |> PG.is True ]
or
 . . . |> PG.is False ]

The decoder does the work.
Sorry for the confusion.

**Comment by john-kelly** [comment]
Glad you figured it out! Might I recommend taking a look at the dev version (on the dev branch) 

Depending on the state of your project, it might make sense to use the upcoming version. I'm working on the release. It's ready for alpha if you're interested

**Comment by jbrgfx** [comment]
Thanks for the heads-up re: the alpha dev branch. Again, thanks for doing
this project as it removes a pain-point or three on some use cases.
