### ISSUE TITLE
Should offset be just an Int?

### ISSUE THREAD

**Issue by randomer** [john-kelly/elm-postgrest#39]
So instead of `Nothing` it would simply be `0`

**Comment by john-kelly** [comment]
this is a good point. 

it's almost a case for bringing back opaque `Limit` and `Offset` 👍  It *might* be a bit weird that the options type would look like:

```elm

{ filters: ...
, orders: ...
, limit: Maybe Int
, offset: Int
}
```

I'm not convinced either way tho.

**Comment by john-kelly** [comment]
This may provide some insight: https://www.postgresql.org/docs/9.6/static/queries-limit.html

**Comment by anderoonies** [comment]
agreed
