### ISSUE TITLE
OR support

### ISSUE THREAD

**Issue by john-kelly** [john-kelly/elm-postgrest#44]
although this is not yet added -- we should start thinking about the API changes necessary for this:

https://github.com/begriffs/postgrest/issues/652

**Comment by begriffs** [comment]
Is this a duplicate issue, or are you kind of starting fresh because the other one has such a long history?

**Comment by begriffs** [comment]
Maybe it makes sense to wait and see if @steve-chavez runs into any implementation details that cause the interface to change slightly from what we discussed in 652.
