### ISSUE TITLE
map...map8 limits

### ISSUE THREAD

**Issue by psfblair** [john-kelly/elm-postgrest#61]
I just ran into my first case of needing to retrieve ten fields in a query. Right now it looks like I have to make two queries, but it would be helpful to find a more general way instead. It's not unusual for rows in a database to have more than eight columns.

**Comment by psfblair** [comment]
I was actually able to retrieve the ten fields without doing two queries by using a nested record as one of the top-level fields, but that's still pretty hacky.

**Comment by john-kelly** [comment]
# Solution
You can define a function `andMap` like so:

```elm
andMap : Selection attributes a -> Selection attributes (a -> b) -> Selection attributes b
andMap =
    map2 (|>)

-- or

andMap : Selection attributes a -> Selection attributes (a -> b) -> Selection attributes b
andMap selectionA selectionAtoB =
    map2 (\a aToB -> aToB a) selectionA selectionAtoB
```

# Example
```elm
Rest.succeed User
    |> andMap (Rest.field .field1)
    |> andMap (Rest.field .field2)
    |> andMap (Rest.field .field3)
    |> andMap (Rest.field .field4)
    |> andMap (Rest.field .field5)
    |> andMap (Rest.field .field6)
    |> andMap (Rest.field .field7)
    |> andMap (Rest.field .field8)
    |> andMap (Rest.field .field9)
    |> ...
```

This function gives you a general way to make `Selection`s out of an arbitrary number of other `Selection`s

# Context
This function is _intentionally_ not exposed by john-kelly/elm-postgrest for the same reasons elm/json does not expose it. There are a few ideas motivating this decision:

1. very easily defined for oneself (shown above)
2. arguable that a record with >8 fields is not the best idea (just a thought! not a fact by any means)
3. functions like this (id. `andMap`, `andField`) _may_ belong in a separate elm-postgrest-extra or elm-postgrest-pipeline package
